### ISSUE TITLE
Tanks are not friendly with rendering

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/Modularity-Core#1]
When a block is above a tank, there is a lost of z fighting. 
![image](https://cloud.githubusercontent.com/assets/2250798/18615986/c2be1b6a-7d70-11e6-972c-6442eebfde8a.png)

**Comment by KitsuneAlex** [comment]
My bad, need to redo some rendering, thanks for letting me know ! will fix it asap !
