### ISSUE TITLE
Buckets can overflow

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/Modularity-Core#2]
If you click on a tank with a bucket of fluid, and the tank is already full, the bucket will place the fluid instead. This can be fixed by adding something like this to the final return statement in `Block#onBlockActivated`. 

```Java
return heldItem != null && !(heldItem.getItem() instanceof ItemBlock);
```

**Comment by KitsuneAlex** [comment]
Thanks for letting me know about that DankHax =D will fix it asap !
